### PR TITLE
Added better error handling support in all views. Base view now has a ha...

### PR DESCRIPTION
**Pull request by jbest84**
...ndleError method that accepts an error object. This will iterate all registered error handlers, which will be an array that is customizable via the 'error_handlers' subset. See _EditBase and tests/View for examples on registering and chaining error handlers. Added a general view "getErrorMessage" which takes an error, and attempts to pull an error messaged based on the http status code and falls back to a general error.
# MBL-10823

@CHenrie Please review

### CODE REVIEW

**Comment by jbest84** [comment]
@CHenrie Also note, only _EditBase as converted as a proof to the new error handling. I will go ahead and convert _ListBase and _DetailBase once this is approved.

**Comment by CHenrie** [comment]
@jbest84  this looks good but should we pull the error handling out as separate mixin or module so it can be re used?

**Comment by jbest84** [comment]
@CHenrie Sure - I don't think the HTTP_STATUS codes really belong under view either. Should we have them live with the mixin or extract into something else?

**Comment by jbest84** [comment]
@CHenrie Re-factored the code out of list and into the mixin (list uses the mixin).

**Comment by CHenrie** [comment]
@jbest84 I Accpet

**Comment by CHenrie** [comment]
@jbest84 Accpeted

**Pull request merged**
